---
- hosts: all
  become: true
  gather_facts: true
  vars:
    print_ansible_facts: false
    check: true
    update_upgrade: false
    debug_output: true
    error_message_1: "No such file or directory"
  tasks:
    - name: Update & Upgrade
      ansible.builtin.shell: |
        sudo apt install -y && sudo apt upgrade -y
      when: update_upgrade
    - name: Check if Docker is Installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: true # to handle failures in case docker is not present
    - ansible.builtin.debug:
        var: output
      when: debug_output
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: output.failed
    - name: Customized Failing Conditions
      ansible.builtin.command: ls /doc.html
      register: output
      failed_when: >
        ((error_message_1 in output.stdout) or (error_message_1 in output.stderr)) and 1 == 1
    - ansible.builtin.debug:
        var: output
    - name: Test Task
      ansible.builtin.shell: echo "Testing Error Handling"